### PR TITLE
Run tests with OpenJDK 7 to verify runtime compatibility

### PR DESCRIPTION
**Pull request by tbroyer**

### CODE REVIEW

**Comment by kenzierocks** [comment]
*watches travis*

**Comment by JakeWharton** [comment]
Looks like you need to skip test compilation as well. Oh, Maven. A better build system would know it already compiled them...

**Comment by kenzierocks** [comment]
Like gradle?

**Comment by tbroyer** [comment]
The problem is the `tools.jar` depends on the `$JAVA_HOME`, so it's different between invocations and Maven then **correctly** recompiles as dependencies have changed.

Invoking `surefire:test` won't run the compile plugin.

**Pull request merged**
